# 02 - Limpieza de datos

## Objetivo

Realizar la limpieza de los datos a partir de los problemas identificados durante la etapa de comprensión, procurando conservar la información original y documentar las decisiones tomadas.

Los principales aspectos identificados que requieren revisión son:

- `TotalCharges` está almacenada como texto aunque conceptualmente es una variable numérica.
- Existen 11 registros con espacios en blanco en `TotalCharges`.
- Los 11 registros anteriores corresponden a clientes con `tenure = 0`.
- `customerID` corresponde a un identificador y no a una característica predictora.
- No se encontraron registros duplicados.
- Las variables categóricas no presentaron inconsistencias evidentes en sus valores.

## 1. Carga de los datos

In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path("../data/raw/Telco-Customer-Churn.csv")

df = pd.read_csv(DATA_PATH)

In [2]:
df_clean = df.copy()

## 2. Tratamiento de `TotalCharges`

Durante la etapa de comprensión de los datos se identificó que `TotalCharges` está almacenada como texto, aunque representa una variable numérica. Además, se encontraron 11 registros con espacios en blanco, todos correspondientes a clientes con `tenure = 0`.

Antes de realizar la conversión se revisarán nuevamente estos registros para definir el tratamiento más adecuado.

In [3]:
df_clean.loc[
    df_clean["TotalCharges"].str.strip().eq(""),
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges"]
]

      customerID  tenure  MonthlyCharges TotalCharges
488   4472-LVYGI       0           52.55
753   3115-CZMZD       0           20.25
936   5709-LVOEQ       0           80.85
1082  4367-NUYAO       0           25.75
1340  1371-DWPAZ       0           56.05
3331  7644-OMVMY       0           19.85
3826  3213-VVOLG       0           25.35
4380  2520-SGTTA       0           20.00
5218  2923-ARZLG       0           19.70
6670  4075-WKNIU       0           73.35
6754  2775-SEFEE       0           61.90

In [4]:
df_clean["TotalCharges"] = pd.to_numeric(
    df_clean["TotalCharges"],
    errors="coerce"
)

In [7]:
df_clean["TotalCharges"].isna().sum()

np.int64(11)

In [8]:
df_clean["TotalCharges"].dtype

dtype('float64')

In [9]:
df_clean.loc[
    df_clean["TotalCharges"].isna(),
    "TotalCharges"
] = 0

In [10]:
df_clean["TotalCharges"].isna().sum()

np.int64(0)

In [11]:
df_clean.loc[
    df_clean["tenure"] == 0,
    ["tenure", "MonthlyCharges", "TotalCharges"]
]

      tenure  MonthlyCharges  TotalCharges
488        0           52.55           0.0
753        0           20.25           0.0
936        0           80.85           0.0
1082       0           25.75           0.0
1340       0           56.05           0.0
3331       0           19.85           0.0
3826       0           25.35           0.0
4380       0           20.00           0.0
5218       0           19.70           0.0
6670       0           73.35           0.0
6754       0           61.90           0.0